/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.guilford.stoprightthere;

import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author kevin
 */
public class StartMenuNew extends javax.swing.JFrame {
    
    JLabel Title = new JLabel();
    Font bigFont = new Font("Dialog", Font.BOLD, 18);
    Font normalFont = new Font("Dialog", Font.BOLD, 12);
    
    /**
     * Creates new form StartMenuNew
     */
    public StartMenuNew() {
        initComponents();
        
        ImageIcon title = new ImageIcon(StartMenuNew.class.getResource("/stopRightThereLogo.jpg")); //no .tourl for ImageIcon
        // ImageIcon title = new ImageIcon("src/main/resources/stopRightThereLogo.jpg");
        Title.setBounds(-50,0,500,500);
        Title.setIcon(title);
        Title.setVisible(true);
        this.add(Title);
        
        startButton.setFocusable(false);
        startButton.setBackground(new Color(255, 255, 255));
        startButton.setBorderPainted(false);
        startButton.setFont(normalFont);
        
        customButton.setFocusable(false);
        customButton.setBackground(new Color(255, 255, 255));
        customButton.setBorderPainted(false);
        customButton.setFont(normalFont);
        
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startButton = new javax.swing.JButton();
        customButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SRT");
        setMaximumSize(new java.awt.Dimension(430, 500));
        setMinimumSize(new java.awt.Dimension(430, 500));
        setPreferredSize(new java.awt.Dimension(430, 500));
        setResizable(false);

        startButton.setText("Start");
        startButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                startButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                startButtonMouseExited(evt);
            }
        });
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        customButton.setText("Information");
        customButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                customButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                customButtonMouseExited(evt);
            }
        });
        customButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(customButton, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(startButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(customButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButtonActionPerformed
        // TODO add your handling code here:
            playHitSound();
            this.dispose();
            new InformationPage();
    }//GEN-LAST:event_customButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
            playHitSound();
            this.dispose();
            // new LevelSelect();
            new LevelSelectNew();
    }//GEN-LAST:event_startButtonActionPerformed

    private void startButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startButtonMouseEntered
        // TODO add your handling code here:
        playHitSound();
        startButton.setFont(bigFont);
        startButton.setBackground(new Color(200, 200, 200));
    }//GEN-LAST:event_startButtonMouseEntered

    private void startButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startButtonMouseExited
        // TODO add your handling code here:
        startButton.setFont(normalFont);
        startButton.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_startButtonMouseExited

    private void customButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customButtonMouseEntered
        // TODO add your handling code here:
        playHitSound();
        customButton.setFont(bigFont);
        customButton.setBackground(new Color(200, 200, 200));
    }//GEN-LAST:event_customButtonMouseEntered

    private void customButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customButtonMouseExited
        // TODO add your handling code here:
        customButton.setFont(normalFont);
        customButton.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_customButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartMenuNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartMenuNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartMenuNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartMenuNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartMenuNew().setVisible(true);
            }
        });
    }
    
    private void playHitSound() {
        //File hitFile = new File("src/main/resources/hitsound.wav");
        File hitFile = new File(StartMenuNew.class.getResource("/hitsound.wav").getFile()); // .toURI() does not work
        AudioInputStream audioStream;
        try {
            audioStream = AudioSystem.getAudioInputStream(hitFile);
            Clip clip = AudioSystem.getClip();
            clip.open(audioStream);
            clip.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
            Logger.getLogger(MusicPlayerThread.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton customButton;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
